title: "Aseem | Data Science Portfolio"
description: "Data Science, AI, Machine Learning, and Design"
url: "https://enmaxxmachiine.github.io"
baseurl: "/data-science-portfolio"
theme: null
markdown: kramdown
