remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: "Aseem | Data Science Portfolio"
description: "Data Science, Machine Learning, AI, and Design"
url: "https://enmaxxmachiine.github.io"
baseurl: "/data-science-portfolio"
theme: null
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
